#!/usr/bin/env bash
# Doska live-preview dev stack.
#
# Previews are temporary and per-mission. There is no permanent dev server on
# this box: offset 0 (5173/3100/5433) is retired and start() refuses it, so a
# mission worktree always takes PORT_OFFSET>=1 and 5173 stays free for Vite's
# stock default. Day-to-day the deployed site is what you look at.
#
# Runs the three processes a preview needs, from whichever worktree this script
# lives in, on ports that never collide with the staging deploy (3000/5432/8080):
#
#   db   PGlite over a Postgres socket   127.0.0.1:5434   (apps/server/pgdata)
#   api  Fastify under `tsx watch`       127.0.0.1:3101   (restarts on server edits)
#   web  Vite dev server + HMR           $WEB_HOST:5173 (HTTPS/HTTP2)
#
# Usage:
#   scripts/dev-preview.sh start | stop | restart | reload | status | logs | check | url
#
# Every preview takes an offset (see CLAUDE.md); a parallel one takes the next:
#   PORT_OFFSET=1 scripts/dev-preview.sh start     # 5174 / 3101 / 5434
#   PORT_OFFSET=2 scripts/dev-preview.sh start     # 5175 / 3102 / 5435
#
#   PORT_OFFSET=1 scripts/dev-preview.sh stop      # when the mission is done
#
# Env overrides: WEB_HOST (default 127.0.0.1), PORT_OFFSET (default 1; 0 refused).
#
# Box-specific values (the address the operator's browser reaches this box on,
# and anything else that should not live in a public repo) go in the main
# worktree's scripts/dev-preview.local.sh — gitignored, sourced below, and shared
# by every worktree:
#
#   WEB_HOST=203.0.113.7
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# The integration checkout and the staging branch. Not about serving anything:
# CANONICAL_ROOT is where every worktree's node_modules symlinks to, so vite's
# fs.allow needs it; it holds the box-local config below; and CANONICAL_BRANCH is
# what `check` measures a mission against. The integration checkout is by
# definition the repo's main worktree, which git reports first; deriving it keeps
# this script path-free.
CANONICAL_ROOT="$(git -C "$ROOT" worktree list --porcelain 2>/dev/null | awk '/^worktree /{print substr($0,10); exit}')"
CANONICAL_ROOT="${CANONICAL_ROOT:-$ROOT}"
CANONICAL_BRANCH="working"

# Untracked, box-specific overrides (WEB_HOST, ...). It lives in the main
# worktree and serves every worktree, so a mission does not need its own copy;
# a per-worktree file still wins if one exists. An explicit env var beats both.
_env_web_host="${WEB_HOST:-}"
for _conf in "$CANONICAL_ROOT/scripts/dev-preview.local.sh" "$ROOT/scripts/dev-preview.local.sh"; do
  # shellcheck source=/dev/null
  [ -f "$_conf" ] && . "$_conf"
done
[ -n "$_env_web_host" ] && WEB_HOST="$_env_web_host"
unset _env_web_host _conf

OFFSET="${PORT_OFFSET:-1}"
WEB_HOST="${WEB_HOST:-127.0.0.1}"
WEB_PORT=$((5173 + OFFSET))
API_PORT=$((3100 + OFFSET))
PG_PORT=$((5433 + OFFSET))

# Node 22 is required (see .nvmrc); the system node is older.
NVM_BIN="$HOME/.nvm/versions/node/v22.23.2/bin"
[ -d "$NVM_BIN" ] && export PATH="$NVM_BIN:$PATH"

# TLS, and it is a performance feature, not a security one. Vite only speaks
# HTTP/2 when server.https is set, and without HTTP/2 a refresh is ~200 separate
# module revalidations squeezed through the browser's 6-connection HTTP/1.1
# limit — ~4s at 60ms RTT, ~8s at 120ms. Over HTTP/2 they multiplex on one
# connection: ~0.9s and ~1.6s. Self-signed, so each browser accepts the warning
# once. Cached outside the repo and outside /tmp so it survives reboots.
CERTDIR="$HOME/.cache/doska-dev-cert"
CERT="$CERTDIR/$WEB_HOST.crt"
CERTKEY="$CERTDIR/$WEB_HOST.key"

STATE="/tmp/doska-preview-$(basename "$ROOT")-$OFFSET"
mkdir -p "$STATE"
LOG="$STATE/dev.log"
PIDFILE="$STATE/dev.pids"

# --- generated dev-only files (both gitignored) -----------------------------

ensure_dev_cert() {
  # Regenerated only when missing or expired. SAN must carry the IP, not just
  # CN — browsers ignore CN for host matching.
  if [ -f "$CERT" ] && [ -f "$CERTKEY" ] \
     && openssl x509 -checkend 604800 -noout -in "$CERT" >/dev/null 2>&1; then
    return 0
  fi
  mkdir -p "$CERTDIR"
  echo "generating self-signed dev cert for $WEB_HOST (valid 825 days)"
  openssl req -x509 -newkey rsa:2048 -nodes -days 825 \
    -keyout "$CERTKEY" -out "$CERT" \
    -subj "/CN=$WEB_HOST" \
    -addext "subjectAltName=IP:$WEB_HOST,DNS:localhost,IP:127.0.0.1" \
    >/dev/null 2>&1 || { echo "failed to generate dev cert"; exit 1; }
  chmod 600 "$CERTKEY"
}

write_server_env() {
  # apps/server/.env is gitignored. Regenerated on every start so the ports
  # always match this script; put nothing here you want to keep.
  cat > "$ROOT/apps/server/.env" <<ENV
# Generated by scripts/dev-preview.sh — regenerated on every start, do not edit.
# Loopback only: this box has public IPs and the API has no business on them.
HOST=127.0.0.1
PORT=$API_PORT
PG_SOCKET_PORT=$PG_PORT
DB_FILE=pgdata
FILE_DIR_OVERRIDE=filedata
AUTH_LOGIN=admin
AUTH_PASSWORD=dev
AUTH_SECRET=dev-only-secret-not-for-production
AUTH_TRUSTED_ORIGINS=https://$WEB_HOST:$WEB_PORT,https://localhost:$WEB_PORT
AUTH_RATE_LIMIT=off
ENV
}

write_vite_config() {
  # The checked-in vite.config.ts hardcodes the API proxy at :3000 — which on
  # this box is the staging server — and binds localhost. This override fixes
  # both. It lives in apps/client/.vite/, already covered by .gitignore, so it
  # never shows up in git status.
  #
  # CLIENT is written as an absolute path on purpose: node_modules here is a
  # symlink into the main checkout, so a __dirname-relative path resolves
  # through the symlink and Vite ends up serving the main checkout's source
  # instead of this worktree's.
  CFGDIR="$ROOT/apps/client/.vite"
  mkdir -p "$CFGDIR"
  cat > "$CFGDIR/vite.config.dev.ts" <<CFG
// Generated by scripts/dev-preview.sh — regenerated on every start.
import path from "path"
import { defineConfig, mergeConfig } from "vite"
import base from "../vite.config"

const CLIENT = "$ROOT/apps/client"

export default mergeConfig(base, defineConfig({
  root: CLIENT,
  resolve: { alias: { "@": path.resolve(CLIENT, "src") } },
  server: {
    // One specific IP, never 0.0.0.0, so a preview can't shadow anything else
    // on this box and two previews can coexist.
    host: "$WEB_HOST",
    allowedHosts: true,
    port: $WEB_PORT,
    strictPort: true,
    // Setting https is what makes Vite serve HTTP/2 (see ensure_dev_cert).
    // The /api proxy below still works: Vite terminates h2 and forwards h1.
    https: { key: "$CERTKEY", cert: "$CERT" },
    // node_modules symlinks into the main checkout, so Vite's default fs.allow
    // (this worktree only) 403s the font files.
    fs: { allow: [CLIENT, "$ROOT", "$CANONICAL_ROOT"] },
    proxy: Object.fromEntries(
      ["/api", "/mcp", "/.well-known"].map((p) => [p, "http://127.0.0.1:$API_PORT"])
    ),
  },
}))
CFG
}

# --- lifecycle ---------------------------------------------------------------

port_up() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null; }

# There is no permanent dev server on this box. Offset 0 (5173/3100/5433) is
# retired: previews are temporary, per-mission, and start at offset 1. 5173 is
# also Vite's stock default, so leaving it free keeps `pnpm dev` unambiguous.
assert_offset_is_a_preview() {
  [ "$OFFSET" = "0" ] || return 0
  cat >&2 <<MSG
refusing: offset 0 (5173/3100/5433) is not used on this box — there is no
permanent dev server. A preview is temporary and belongs to one mission
worktree, so give it an offset:

  PORT_OFFSET=1 scripts/dev-preview.sh start      # 5174 / 3101 / 5434
  PORT_OFFSET=2 scripts/dev-preview.sh start      # 5175 / 3102 / 5435

Day-to-day, the deployed site is the thing to look at. See CLAUDE.md.
MSG
  exit 1
}

# The two things a running stack cannot hot-reload, fingerprinted separately
# because they need very different responses. Recorded at start, compared by
# `reload` after an integration.
migrations_fingerprint() {
  cat "$ROOT/apps/server/drizzle/meta/_journal.json" 2>/dev/null \
    | sha256sum | cut -d' ' -f1
}
deps_fingerprint() {
  {
    cat "$ROOT/pnpm-lock.yaml"
    find "$ROOT/apps" "$ROOT/packages" -maxdepth 2 -name package.json -exec cat {} +
  } 2>/dev/null | sha256sum | cut -d' ' -f1
}

# Keeping a preview in step with git. The hooks live in the COMMON git dir, so
# one install covers every worktree of this repo — and each hook acts on the
# worktree the git command actually ran in, at whatever offsets that worktree
# has running. Installing from the canonical checkout is enough for all of them.
#
#   post-merge     an integration landed  -> reload (fingerprint decides)
#   post-checkout  a branch switch        -> reload
#   post-rewrite   a rebase               -> RESTART, unconditionally
#
# A rebase is why post-rewrite is separate. It rewrites the tree under a running
# Vite, which applies partial HMR updates and can leave the module graph
# initialising out of order — observed as `runtime used before installRuntime()`
# from packages/core, and a white page that survives a refresh. HMR can patch
# edits; it cannot recover a history rewrite. Only a restart clears it.
install_preview_hooks() {
  local common hook marker
  common="$(git -C "$ROOT" rev-parse --git-common-dir 2>/dev/null)" || return 0
  case "$common" in /*) ;; *) common="$ROOT/$common" ;; esac
  [ -d "$common/hooks" ] || return 0
  marker="# managed by scripts/dev-preview.sh"
  for hook in post-merge post-checkout post-rewrite; do
    if [ -e "$common/hooks/$hook" ] && ! grep -qF "$marker" "$common/hooks/$hook" 2>/dev/null; then
      echo "note: $common/hooks/$hook exists and is not ours — leaving it alone;"
      echo "      run 'scripts/dev-preview.sh reload' by hand after an integration."
      continue
    fi
    # Written via a temp file and mv(1): the hook calls back into this script,
    # which reinstalls the hooks — truncating a file bash is still reading would
    # corrupt the run. Replacing the inode leaves it intact.
    cat > "$common/hooks/$hook.new" <<HOOK
#!/usr/bin/env bash
$marker — keep this worktree's preview in step with git.
KIND=$hook

# git exports GIT_DIR/GIT_WORK_TREE/GIT_INDEX_FILE into hooks, which would
# otherwise override the -C of every git command below.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_PREFIX

# git runs these hooks with cwd at the top of the working tree the command ran
# in — that is how a hook shared by every worktree knows which preview to touch.
top="\$(pwd -P)"
[ -x "\$top/scripts/dev-preview.sh" ] || exit 0

gitdir="\$(git -C "\$top" rev-parse --git-dir 2>/dev/null)" || exit 0
case "\$gitdir" in /*) ;; *) gitdir="\$top/\$gitdir" ;; esac

# Mid-rebase, git fires post-checkout once per replayed commit. Restarting a
# stack on each of those would be absurd; post-rewrite handles it once at the
# end. post-rewrite is exempt from this check because git still has
# \$gitdir/rebase-merge on disk when it runs the hook (measured) — treating that
# as "in progress" would skip the very case the hook exists for.
if [ "\$KIND" != post-rewrite ] \\
   && { [ -d "\$gitdir/rebase-merge" ] || [ -d "\$gitdir/rebase-apply" ]; }; then
  exit 0
fi

verb=reload
if [ "\$KIND" = post-rewrite ]; then
  # post-rewrite also fires for \`commit --amend\` (\$1 = amend), which is an
  # ordinary edit HMR handles fine. Only a rebase needs the restart.
  [ "\$1" = rebase ] || exit 0
  verb=restart
fi

# Only offsets that are actually running: dev.pids exists while a stack is up,
# so this never starts a preview nobody asked for. Never block the git command.
#
# The offset must parse as digits. The canonical checkout's basename is a
# PREFIX of other worktrees' (doska / doska-newfeatures), so the glob alone
# matches a sibling's state dir and \`\${x##*-}\` reads its offset as
# "newfeatures-1". Left unchecked, a post-rewrite there would \`restart\` the
# canonical root onto the sibling's ports and fight its live preview.
base="\$(basename "\$top")"
for pids in /tmp/doska-preview-"\$base"-*/dev.pids; do
  [ -e "\$pids" ] || continue
  dir="\${pids%/dev.pids}"
  off="\${dir##*/}"; off="\${off#doska-preview-\$base-}"
  case "\$off" in ''|*[!0-9]*) continue ;; esac
  PORT_OFFSET="\$off" "\$top/scripts/dev-preview.sh" "\$verb" || true
done
exit 0
HOOK
    chmod +x "$common/hooks/$hook.new"
    mv -f "$common/hooks/$hook.new" "$common/hooks/$hook"
  done
}

start() {
  if running; then echo "already running"; status; return 0; fi
  assert_offset_is_a_preview
  # A second preview means a second *worktree*. Two offsets in one worktree
  # would fight over apps/server/.env and apps/client/.vite/, and one api would
  # be restarted onto the other's port by its own watcher.
  for other in /tmp/doska-preview-"$(basename "$ROOT")"-*/dev.pids; do
    [ -e "$other" ] || continue
    dir="${other%/dev.pids}"; off="${dir##*/}"; off="${off#doska-preview-$(basename "$ROOT")-}"
    case "$off" in ''|*[!0-9]*) continue ;; esac
    [ "$off" = "$OFFSET" ] && continue
    echo "refusing: offset $off is already running in this worktree ($ROOT)."
    echo "Run the second offset from a different worktree — see CLAUDE.md."
    exit 1
  done
  : > "$LOG"
  ensure_dev_cert
  write_server_env
  write_vite_config
  : > "$PIDFILE"
  deps_fingerprint > "$STATE/deps.sha"
  migrations_fingerprint > "$STATE/migrations.sha"
  install_preview_hooks

  cd "$ROOT/apps/server" || exit 1
  setsid node_modules/.bin/tsx --env-file-if-exists=.env src/serve-dev.ts >> "$LOG" 2>&1 &
  echo $! >> "$PIDFILE"

  for _ in $(seq 1 60); do port_up "$PG_PORT" && break; sleep 0.5; done

  DATABASE_URL="postgres://127.0.0.1:$PG_PORT/postgres" \
    setsid node_modules/.bin/tsx watch --env-file-if-exists=.env src/index.ts >> "$LOG" 2>&1 &
  echo $! >> "$PIDFILE"

  cd "$ROOT/apps/client" || exit 1
  setsid node_modules/.bin/vite --config "$CFGDIR/vite.config.dev.ts" >> "$LOG" 2>&1 &
  echo $! >> "$PIDFILE"

  sleep 8
  status
}

stop() {
  if [ -f "$PIDFILE" ]; then
    while read -r p; do
      [ -n "$p" ] || continue
      kill -- -"$p" 2>/dev/null || kill "$p" 2>/dev/null
    done < "$PIDFILE"
    rm -f "$PIDFILE"
  fi
  sleep 1
  echo "stopped"
}

# `reload` is the post-integration step: Vite HMR and `tsx watch` have already
# picked up every source file the merge changed, so the only question left is
# whether migrations or dependencies moved — those a running stack cannot absorb.
#
# Migrations: restart, they run at server boot.
# Dependencies: do NOT install here. `pnpm install` rewrites the shared
# node_modules store that every worktree symlinks into, and a running preview
# in ANY worktree dies mid-resolve when it does — measured, not theoretical.
# Restarting this stack would recover only this one. So say what is needed and
# let the operator run it once, when no one is mid-review.
reload() {
  if ! running; then
    echo "reload: preview is not running — nothing to reload"
    status
    return 0
  fi
  local deps_now deps_prev mig_now mig_prev
  deps_now="$(deps_fingerprint)";      deps_prev="$(cat "$STATE/deps.sha" 2>/dev/null || echo none)"
  mig_now="$(migrations_fingerprint)"; mig_prev="$(cat "$STATE/migrations.sha" 2>/dev/null || echo none)"

  if [ "$deps_now" != "$deps_prev" ]; then
    cat <<MSG

  ┌─ dependencies changed in this integration ────────────────────────────┐
  │ Run this once, when no preview is mid-review — it rewrites the shared │
  │ node_modules store and briefly kills EVERY running preview on the box:│
  │                                                                       │
  │   cd $CANONICAL_ROOT && CI=true pnpm install
  │   $CANONICAL_ROOT/scripts/dev-preview.sh restart
  │                                                                       │
  │ Every other worktree's preview needs a restart after it too.          │
  └───────────────────────────────────────────────────────────────────────┘

MSG
  fi

  if [ "$mig_now" != "$mig_prev" ]; then
    echo "reload: migrations changed — restarting so they run at server boot"
    stop
    start
    return 0
  fi

  echo "reload: no restart needed — Vite HMR and tsx watch already serve the current checkout"
  status
}

running() {
  [ -f "$PIDFILE" ] || return 1
  while read -r p; do kill -0 "$p" 2>/dev/null || return 1; done < "$PIDFILE"
  return 0
}

status() {
  printf 'db  (%s):        %s\n' "$PG_PORT" "$(port_up "$PG_PORT" && echo up || echo DOWN)"
  printf 'api (%s):        %s\n' "$API_PORT" "$(curl -s -m 3 "http://127.0.0.1:$API_PORT/api/version" || echo DOWN)"
  printf 'web (%s:%s): %s\n' "$WEB_HOST" "$WEB_PORT" \
    "$(curl -sk -m 3 -o /dev/null -w '%{http_code}' "https://$WEB_HOST:$WEB_PORT/" || echo DOWN)"
  printf 'url:               %s\n' "https://$WEB_HOST:$WEB_PORT/"
}

# `check` is the pre-flight a session runs before starting a feature: is this
# worktree free to work in, and is it on current main?
check() {
  cd "$ROOT" || exit 1
  local branch dirty behind ahead verdict=CLEAN
  branch="$(git rev-parse --abbrev-ref HEAD)"
  dirty="$(git status --porcelain)"
  read -r behind ahead < <(git rev-list --left-right --count "$CANONICAL_BRANCH"...HEAD | tr '\t' ' ')

  echo "worktree: $ROOT"
  echo "branch:   $branch"
  if [ "$(cd "$ROOT" && pwd -P)" = "$(cd "$CANONICAL_ROOT" 2>/dev/null && pwd -P)" ]; then
    echo "role:     integration checkout — integrate here, do not develop here"
  else
    echo "role:     mission worktree — preview with PORT_OFFSET=1 while you work on it"
  fi
  if [ -n "$dirty" ]; then
    verdict=DIRTY
    echo "state:    DIRTY — unfinished work lives here, do NOT overwrite it:"
    echo "$dirty" | sed 's/^/            /'
  else
    echo "state:    clean"
  fi
  echo "vs $CANONICAL_BRANCH: $behind behind, $ahead ahead"
  [ "$behind" != "0" ] && verdict="${verdict}/BEHIND"
  echo "verdict:  $verdict"
  echo
  status
}

case "${1:-status}" in
  start) start ;;
  stop) stop ;;
  restart) stop; start ;;
  reload) reload ;;
  status) status ;;
  check) check ;;
  logs) tail -f "$LOG" ;;
  url) echo "https://$WEB_HOST:$WEB_PORT/" ;;
  *) echo "usage: $0 start|stop|restart|reload|status|check|logs|url"; exit 1 ;;
esac
