#!/usr/bin/env bash
# Doska live-preview dev stack.
#
# Runs the three processes a preview needs, from whichever worktree this script
# lives in, on ports that never collide with the staging deploy (3000/5432/8080):
#
#   db   PGlite over a Postgres socket   127.0.0.1:5433   (apps/server/pgdata)
#   api  Fastify under `tsx watch`       127.0.0.1:3100   (restarts on server edits)
#   web  Vite dev server + HMR           $WEB_HOST:5173
#
# Usage:
#   scripts/dev-preview.sh start | stop | restart | status | logs | check | url
#
# Second preview, for a parallel feature in another worktree (see CLAUDE.md):
#   PORT_OFFSET=1 scripts/dev-preview.sh start     # 5174 / 3101 / 5434
#
# Env overrides: WEB_HOST (default 127.0.0.1), PORT_OFFSET (default 0).
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OFFSET="${PORT_OFFSET:-0}"
WEB_HOST="${WEB_HOST:-127.0.0.1}"
WEB_PORT=$((5173 + OFFSET))
API_PORT=$((3100 + OFFSET))
PG_PORT=$((5433 + OFFSET))

# Node 22 is required (see .nvmrc); the system node is older.
NVM_BIN="$HOME/.nvm/versions/node/v22.23.2/bin"
[ -d "$NVM_BIN" ] && export PATH="$NVM_BIN:$PATH"

STATE="/tmp/doska-preview-$(basename "$ROOT")-$OFFSET"
mkdir -p "$STATE"
LOG="$STATE/dev.log"
PIDFILE="$STATE/dev.pids"

# --- generated dev-only files (both gitignored) -----------------------------

write_server_env() {
  # apps/server/.env is gitignored. Regenerated on every start so the ports
  # always match this script; put nothing here you want to keep.
  cat > "$ROOT/apps/server/.env" <<ENV
# Generated by scripts/dev-preview.sh — regenerated on every start, do not edit.
# Loopback only: this box has public IPs and the API has no business on them.
HOST=127.0.0.1
PORT=$API_PORT
PG_SOCKET_PORT=$PG_PORT
DB_FILE=pgdata
FILE_DIR_OVERRIDE=filedata
AUTH_LOGIN=admin
AUTH_PASSWORD=dev
AUTH_SECRET=dev-only-secret-not-for-production
AUTH_TRUSTED_ORIGINS=http://$WEB_HOST:$WEB_PORT,http://localhost:$WEB_PORT
AUTH_RATE_LIMIT=off
ENV
}

write_vite_config() {
  # The checked-in vite.config.ts hardcodes the API proxy at :3000 — which on
  # this box is the staging server — and binds localhost. This override fixes
  # both. It lives in apps/client/.vite/, already covered by .gitignore, so it
  # never shows up in git status.
  #
  # CLIENT is written as an absolute path on purpose: node_modules here is a
  # symlink into the main checkout, so a __dirname-relative path resolves
  # through the symlink and Vite ends up serving the main checkout's source
  # instead of this worktree's.
  CFGDIR="$ROOT/apps/client/.vite"
  mkdir -p "$CFGDIR"
  cat > "$CFGDIR/vite.config.dev.ts" <<CFG
// Generated by scripts/dev-preview.sh — regenerated on every start.
import path from "path"
import { defineConfig, mergeConfig } from "vite"
import base from "../vite.config"

const CLIENT = "$ROOT/apps/client"

export default mergeConfig(base, defineConfig({
  root: CLIENT,
  resolve: { alias: { "@": path.resolve(CLIENT, "src") } },
  server: {
    // One specific IP, never 0.0.0.0, so a preview can't shadow anything else
    // on this box and two previews can coexist.
    host: "$WEB_HOST",
    allowedHosts: true,
    port: $WEB_PORT,
    strictPort: true,
    // node_modules symlinks into the main checkout, so Vite's default fs.allow
    // (this worktree only) 403s the font files.
    fs: { allow: [CLIENT, "$ROOT", "$HOME/doska"] },
    proxy: Object.fromEntries(
      ["/api", "/mcp", "/.well-known"].map((p) => [p, "http://127.0.0.1:$API_PORT"])
    ),
  },
}))
CFG
}

# --- lifecycle ---------------------------------------------------------------

port_up() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null; }

start() {
  if running; then echo "already running"; status; return 0; fi
  # A second preview means a second *worktree*. Two offsets in one worktree
  # would fight over apps/server/.env and apps/client/.vite/, and the offset-0
  # api would be restarted onto the wrong port by its own watcher.
  if [ "$OFFSET" != "0" ] && [ -f "/tmp/doska-preview-$(basename "$ROOT")-0/dev.pids" ]; then
    echo "refusing: offset 0 is already running in this worktree ($ROOT)."
    echo "Run the offset from a different worktree — see CLAUDE.md."
    exit 1
  fi
  : > "$LOG"
  write_server_env
  write_vite_config
  : > "$PIDFILE"

  cd "$ROOT/apps/server" || exit 1
  setsid node_modules/.bin/tsx --env-file-if-exists=.env src/serve-dev.ts >> "$LOG" 2>&1 &
  echo $! >> "$PIDFILE"

  for _ in $(seq 1 60); do port_up "$PG_PORT" && break; sleep 0.5; done

  DATABASE_URL="postgres://127.0.0.1:$PG_PORT/postgres" \
    setsid node_modules/.bin/tsx watch --env-file-if-exists=.env src/index.ts >> "$LOG" 2>&1 &
  echo $! >> "$PIDFILE"

  cd "$ROOT/apps/client" || exit 1
  setsid node_modules/.bin/vite --config "$CFGDIR/vite.config.dev.ts" >> "$LOG" 2>&1 &
  echo $! >> "$PIDFILE"

  sleep 8
  status
}

stop() {
  if [ -f "$PIDFILE" ]; then
    while read -r p; do
      [ -n "$p" ] || continue
      kill -- -"$p" 2>/dev/null || kill "$p" 2>/dev/null
    done < "$PIDFILE"
    rm -f "$PIDFILE"
  fi
  sleep 1
  echo "stopped"
}

running() {
  [ -f "$PIDFILE" ] || return 1
  while read -r p; do kill -0 "$p" 2>/dev/null || return 1; done < "$PIDFILE"
  return 0
}

status() {
  printf 'db  (%s):        %s\n' "$PG_PORT" "$(port_up "$PG_PORT" && echo up || echo DOWN)"
  printf 'api (%s):        %s\n' "$API_PORT" "$(curl -s -m 3 "http://127.0.0.1:$API_PORT/api/version" || echo DOWN)"
  printf 'web (%s:%s): %s\n' "$WEB_HOST" "$WEB_PORT" \
    "$(curl -s -m 3 -o /dev/null -w '%{http_code}' "http://$WEB_HOST:$WEB_PORT/" || echo DOWN)"
  printf 'url:               %s\n' "http://$WEB_HOST:$WEB_PORT/"
}

# `check` is the pre-flight a session runs before starting a feature: is this
# worktree free to work in, and is it on current main?
check() {
  cd "$ROOT" || exit 1
  local branch dirty behind ahead verdict=CLEAN
  branch="$(git rev-parse --abbrev-ref HEAD)"
  dirty="$(git status --porcelain)"
  git fetch -q origin main 2>/dev/null
  read -r behind ahead < <(git rev-list --left-right --count origin/main...HEAD | tr '\t' ' ')

  echo "worktree: $ROOT"
  echo "branch:   $branch"
  if [ -n "$dirty" ]; then
    verdict=DIRTY
    echo "state:    DIRTY — unfinished work lives here, do NOT overwrite it:"
    echo "$dirty" | sed 's/^/            /'
  else
    echo "state:    clean"
  fi
  echo "vs main:  $behind behind, $ahead ahead"
  [ "$behind" != "0" ] && verdict="${verdict}/BEHIND"
  echo "verdict:  $verdict"
  echo
  status
}

case "${1:-status}" in
  start) start ;;
  stop) stop ;;
  restart) stop; start ;;
  status) status ;;
  check) check ;;
  logs) tail -f "$LOG" ;;
  url) echo "http://$WEB_HOST:$WEB_PORT/" ;;
  *) echo "usage: $0 start|stop|restart|status|check|logs|url"; exit 1 ;;
esac
